### Univariate linear regression using gradient descent


In [1]:
import matplotlib.pyplot as plt
import numpy as np
import torch

%matplotlib inline

In [2]:
def sigmoid_activation(x):
    return 1/(1+torch.exp(-x))


def relu_activation(x):
    if x < 0:
        return x*(-1)
    else:
        return x

In [38]:
torch.manual_seed(7)

inputs = torch.randn(1,5)
print inputs

weights = torch.randn_like(inputs)
bias = torch.randn(1,1)
print weights
print bias

print inputs.shape
print weights.shape
print bias.shape

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])
torch.Size([1, 5])
torch.Size([1, 5])
torch.Size([1, 1])


In [5]:
# using dot product

y_sigmoid = sigmoid_activation(torch.sum(inputs*weights) + bias)
y_relu = relu_activation(torch.sum(inputs*weights) + bias)
print y_sigmoid
print y_relu

tensor([[0.1595]])
tensor([[1.6619]])


In [6]:
# using matrix multiplication

weights_reshaped = weights.reshape((5,1))
print weights_reshaped.shape

y_sigmoid = sigmoid_activation(torch.mm(inputs,weights_reshaped) + bias)
y_relu = relu_activation(torch.mm(inputs,weights_reshaped) + bias)
print y_sigmoid
print y_relu


torch.Size([5, 1])
tensor([[0.1595]])
tensor([[1.6619]])


In [11]:
# A small neural network with 3 input units, 1 hidden layer of 2 units, and one output unit

torch.manual_seed(7)

inputs = torch.randn((,3))
W1 = torch.randn((3,2))
W2 = torch.randn((2,1))
B1 = torch.randn((1,2))
B2 = torch.randn((1,1))

hidden_layer = sigmoid_activation(torch.mm(inputs,W1) + B1)
y = sigmoid_activation(torch.mm(hidden_layer,W2) + B2)

print hidden_layer
print y

y_np = y.numpy()
print y_np


tensor([[0.6813, 0.4355]])
tensor([[0.3171]])
[[0.31708315]]


In [61]:
# Logical AND with pytorch

inputs = torch.tensor([[1.0],[1.0],[1.0]]) # 1, x1 , x2
W1 = torch.tensor([[-30.0],[20.0],[20.0]]) # weights for logical AND

print inputs.shape
print W1.shape

output_0_0 = sigmoid_activation(torch.mm(W1.reshape((1,3)),torch.tensor([[1.0],[0.0],[0.0]])))
print output_0_0

output_0_1 = sigmoid_activation(torch.mm(W1.reshape((1,3)),torch.tensor([[1.0],[0.0],[1.0]])))
print output_0_1

output_1_0 = sigmoid_activation(torch.mm(W1.reshape((1,3)),torch.tensor([[1.0],[1.0],[0.0]])))
print output_1_0

output_1_1 = sigmoid_activation(torch.mm(W1.reshape((1,3)),torch.tensor([[1.0],[1.0],[1.0]])))
print output_1_1




torch.Size([3, 1])
torch.Size([3, 1])
tensor([[1.0000]])
tensor([[9.3576e-14]])
tensor([[4.5398e-05]])
tensor([[4.5398e-05]])
tensor([[1.0000]])


In [68]:
# MNIST
%config InlineBackned.figure_format = 'retina'

from torchvision import datasets, transforms

transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5)),])

trainset = datasets.MNIST('MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)







Using downloaded and verified file: MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz
Extracting MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz


IOError: Not a gzipped file

In [86]:
# network done from scratch

def softmax_activation(x):
    return torch.exp(x)/torch.sum(torch.exp(x), dim=1).view(-1,1)



torch.manual_seed(7)
images = torch.randn(64,1,28,28)

images_flattened = images.reshape(64,784)
print images.shape
print images_flattened.shape


W1 = torch.randn(784,256)
W2 = torch.randn(256,10)
B1 = torch.randn(1,256)
B2 = torch.randn(1,10)

hidden_layer = sigmoid_activation(torch.mm(images_flattened,W1) + B1)
y = softmax_activation(torch.mm(hidden_layer,W2) + B2)

print hidden_layer.shape
print y.sum(dim=1)
print y.shape








torch.Size([64, 1, 28, 28])
torch.Size([64, 784])
torch.Size([64, 256])
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000])
torch.Size([64, 10])


In [93]:
# network using nn from pytorch

from torch import nn

class Network_MNIST(nn.Module):
    
    def __init__(self):
        super(Network_MNIST, self).__init__()
        self.hidden_layer = nn.Linear(784, 256)
        self.output_layer = nn.Linear(256, 10)
    
        self.sigmoid_activation = nn.Sigmoid()
        self.softmax_activation = nn.Softmax(dim=1)
    
    def forward_prop(self,x):
        
        x = self.hidden_layer(x)
        x = self.sigmoid_activation(x)
        x = self.output_layer(x)
        x = self.softmax_activation(x)
        
        return x
        






In [94]:
model1 = Network_MNIST()
model1

Network_MNIST(
  (hidden_layer): Linear(in_features=784, out_features=256, bias=True)
  (output_layer): Linear(in_features=256, out_features=10, bias=True)
  (sigmoid_activation): Sigmoid()
  (softmax_activation): Softmax()
)

In [97]:
# network using nn.functionnal

import torch.nn.functional as F

class Network_MNIST_F(nn.Module):
    
    def __init__(self):
        super(Network_MNIST_F, self).__init__()
        self.hidden_layer = nn.Linear(784, 256)
        self.output_layer = nn.Linear(256, 10)
    
    def forward_prop(self,x):
        
        x = F.sigmoid(self.hidden_layer(x))
        x = F.softmax(self.output_layer(x), dim=1)
        
        return x
        


In [98]:
model2 = Network_MNIST_F()
model2

Network_MNIST_F(
  (hidden_layer): Linear(in_features=784, out_features=256, bias=True)
  (output_layer): Linear(in_features=256, out_features=10, bias=True)
)

In [99]:
# defining new network with 784 inputs, h1 128 relu, h2 64 relu, output 10 softmax, 1 loss layer cross entropy



class Network_3(nn.Module):
    
    def __init__(self):
        super(Network_3, self).__init__()
        self.hidden_layer_1 = nn.Linear(784, 128)
        self.hidden_layer_2 = nn.Linear(128, 64)
        self.output_layer = nn.Linear(64, 10)
        self.loss_layer = nn.Linear(10, 1)
    
    def forward_prop(self,x):
        
        x = F.relu(self.hidden_layer_1(x))
        x = F.relu(self.hidden_layer_2(x))
        x = F.softmax(self.output_layer(x), dim=1)
        
        return x

In [100]:
model3 = Network_3()
model3

Network_3(
  (hidden_layer_1): Linear(in_features=784, out_features=128, bias=True)
  (hidden_layer_2): Linear(in_features=128, out_features=64, bias=True)
  (output_layer): Linear(in_features=64, out_features=10, bias=True)
  (loss_layer): Linear(in_features=10, out_features=1, bias=True)
)

In [90]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t.t()
print('Tensor shape:', t.shape)

('Tensor shape:', torch.Size([2, 3]))
